### DISCUSSION TITLE
bypass4netns benchmark result (with multiple EC2 instances)

### DISCUSSION THREAD

**Discussion by AkihiroSuda** [rootless-containers/usernetes#329] [Show and tell]
- EC2, m7i.2xlarge
- Ubuntu 22.04, nerdctl v2 beta4, bypass4netns v0.4.1, Usernetes gen2-v20240410.0
- Workload: iperf3 (TCP)

  | slirp4netns | bypass4netns
-- | -- | --
Pod → Pod (same node) | 37.6 Gbps | 37.6 Gbps
Pod → Pod (different node) | 1.40 Gbps | 1.41 Gbps
Pod → NodePort   (same node) | 1.28 Gbps | 49.9 Gbps 🆙 
Pod → NodePort   (different node) | 1.47 Gbps | 9.53 Gbps 🆙 
Host → NodePort   (same node) | 50.2 Gbps | 49.4 Gbps
Host → NodePort   (different node) | 9.53 Gbps | 9.52 Gbps

~Note: NodePort seems unstable, even without bypass4netns~ (iperf3 seems to need `sessionAffinity: ClientIP`)

<details><summary><code>iperf3.yaml</code></summary>

<p>

```yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf3
  labels:
    app: iperf3
spec:
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      nodeName: u7s-usernetes-vm0
      containers:
        - name: iperf3
          image: alpine:3.19
          args: ["/bin/sh", "-euxc", "apk add iperf3 && iperf3 -s"]
          ports:
            - containerPort: 5201
              name: iperf
              protocol: TCP
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf3-another
  labels:
    app: iperf3-another
spec:
  selector:
    matchLabels:
      app: iperf3-another
  template:
    metadata:
      labels:
        app: iperf3-another
    spec:
      nodeName: u7s-usernetes-vm1
      containers:
        - name: iperf3
          image: alpine:3.19
          args: ["/bin/sh", "-euxc", "apk add iperf3 && iperf3 -s"]
          ports:
            - containerPort: 5201
              name: iperf
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3
spec:
  type: NodePort
  selector:
    app: iperf3
  sessionAffinity: ClientIP
  ports:
    - protocol: TCP
      port: 5201
      targetPort: 5201
      nodePort: 30123
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-another
spec:
  type: NodePort
  selector:
    app: iperf3-another
  sessionAffinity: ClientIP
  ports:
    - protocol: TCP
      port: 5201
      targetPort: 5201
      nodePort: 30124
```

</p>

- `nodeName` is hard-coded for ease of benchmarking
- The number of the replicas has to be increased for benchmarking Pod-to-Pod

</details>
