### ISSUE TITLE
add cri-o

### ISSUE THREAD

**Issue by AkihiroSuda** [rootless-containers/usernetes#11]
ref: https://github.com/kubernetes-incubator/cri-o/pull/1729

cc @giuseppe

**Comment by giuseppe** [comment]
CRI-O is a bit more painful to install locally, I'll try that once https://github.com/kubernetes-incubator/cri-o/pull/1729 lands.  With that version of CRI-O I am able to start usernetes using this taskfile:

```yaml
# Usernetes: CRI-O & Kubernetes without the root privileges
#
# You need to use `run.sh` for executing these tasks.
# Please refer to `README.md` for the usage.
version: '2'

output: prefixed

tasks:
  crio:
    env:
      _CRIO_ROOTLESS: 1
    cmds:
      - test $_USERNETES_CHILD
      - mkdir -p $HOME/.local/share/containers
      - |
        /usr/bin/crio \
        --runroot $XDG_RUNTIME_DIR/crio \
        --root $HOME/.local/share/containers/storage --cgroup-manager=cgroupfs \
        --storage-driver vfs --runtime /usr/bin/runc
  etcd:
    cmds:
      - test $_USERNETES_CHILD
      - etcd --data-dir $HOME/.local/share/usernetes/etcd
  kube-apiserver:
    cmds:
      - test $_USERNETES_CHILD
      - |
        hyperkube kube-apiserver \
        --etcd-servers http://127.0.0.1:2379 \
        --admission-control=AlwaysAdmit \
        --authorization-mode=AlwaysAllow \
        --anonymous-auth=true
  kube-controller-manager:
    cmds:
      - test $_USERNETES_CHILD
      - hyperkube kube-controller-manager --master http://localhost:8080
  kube-scheduler:
    cmds:
      - test $_USERNETES_CHILD
      - hyperkube kube-scheduler --master http://localhost:8080
  kubelet:
    cmds:
      - test $_USERNETES_CHILD
      - |
        hyperkube kubelet \
        --container-runtime remote \
        --container-runtime-endpoint unix:///run/crio/crio.sock \
        --cert-dir $HOME/.config/usernetes/pki \
        --root-dir $HOME/.local/share/usernetes/kubelet \
        --log-dir $HOME/.local/share/usernetes/kubelet-log \
        --volume-plugin-dir $HOME/.local/share/usernetes/kubelet-plugins-exec \
        --kubeconfig localhost.kubeconfig \
        --anonymous-auth=true \
        --authorization-mode=AlwaysAllow \
        --fail-swap-on=false \
        --feature-gates DevicePlugins=false
  default:
    deps: [crio,etcd,kube-apiserver,kube-controller-manager,kube-scheduler,kubelet]

```

and successfully deploy a simple POD like:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: nginx
        image: docker.io/nginx:1.8.1
        command: ["sh"]
        args: ["-c", "nginx -g 'daemon off; error_log /dev/stdout debug;'"]
        ports:
        - containerPort: 80
```

(without sh running as PID 1, nginx dies with SIGCHLD, so I added the extra hack but I guess this is out of the scope for this PR)

/cc @mrunalp @rhatdan
