### ISSUE TITLE
Exposing pod service with Ingress

### ISSUE THREAD

**Issue by vsoch** [rootless-containers/usernetes#318]
I know that I need to add additional ports to the docker-compose.yaml for them to be exposed (e.g., a service running in a pod). I did this for several, and tried both with and without https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml but I can't seem to access the service. For detail, the service (confirmed working with this setup on my local machine, and inside the pod via a curl to localhost) should be exposed with this service setup:

```
apiVersion: v1
kind: Service
metadata:
  name: ml-service
spec:
  selector:
    run: ml-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ml-service
            port: 
              number: 8080
```
And the selector for the pod:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-server
spec:
  selector:
    matchLabels:
      run: ml-service
```
But it can't seem to see it:

```
$ curl  localhost/api/
curl: (7) Failed to connect to localhost port 80 after 0 ms: Connection refused

$ curl -k localhost:8080/api/
curl: (7) Failed to connect to localhost port 8080 after 0 ms: Connection refused
```
From the inside the pod, this is what we should see (but with the service, without 8080):

![image](https://github.com/rootless-containers/usernetes/assets/814322/32daee09-d8a4-4892-9344-8ce4df41e768)

I'm thinking about this more, and I think I need to force a recreate of the container (I just restarted) so I'll try that and report back! I didn't do that because I was afraid I'd lose the `join-command` but that's not a big deal to redo. E.g.,

```
docker compose up -d --force-recreate
```
